version: '3.4'
services:
  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   environment:
  #     SA_PASSWORD: "Sa123456"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - 1433:1433
  #   networks:
  #     - local-dev-app

  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
      ports:
        - 27017:27017
      networks:
        - local-dev-app

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #   networks:
  #     - local-dev-app


networks:
  local-dev-app: